### ISSUE TITLE
remove hardcoded channel & guild ids

### ISSUE THREAD

**Issue by WolffM** [erinwolff/trivia-bot#2]

**Comment by RhoMancer** [comment]
What is happening? Can you explain steps to reproduce?

**Comment by WolffM** [comment]
Please provide your system specs, browser version, network latency, and astrological sign for further instructions.

**Comment by RhoMancer** [comment]
Is this BAU or do we need new requirements? Also can someone get PO to assign severity/priority?

**Comment by erinwolff** [comment]
confirmed there are no hardcoded values outside of register-commands.js. this has no effect on the bot as a whole
